#!/usr/bin/python3
import sys
def print_result(num, answers):
    for answer in answers:
        if answer.startswith(f"{num}="):
            print(answer[:-1])
            return True
    return False

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)
file_path = sys.argv[1]

try:
    with open(file_path, "r") as inputs:
        with open("answers", "r") as answers:
            for num in inputs:
                if num[-1] == "\n":
                    num = num[:-1]
                if not print_result(num, answers):
                    print(f"{num}={num}*1")
except FileNotFoundError:
    print(f"File '{file_path}' not found.")
except ValueError:
    print("Invalid number in the file.")
